style: flatten release script switch statement

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -9,12 +9,12 @@ function main()
 {
     [[ -z ${ git status --porcelain; } ]] || exit
 
-    local -r opts=${ getopt -o "" -l "no-dry-run" -- "$@"; } || exit
+    local opts=${ getopt -o "" -l "no-dry-run" -- "$@"; } || exit
     local dryRun=1
     local version=${ git describe --tags --abbrev=0; }
     local semverType major minor patch tidy
 
-    eval set -- "$opts"
+    eval set -- "$opts"; opts=
 
     while true; do
         case "$1" in
@@ -35,22 +35,10 @@ function main()
     IFS=. read -r major minor patch <<<"${version:1}"
 
     case "$semverType" in
-        major)
-            ((major++))
-            minor=0
-            patch=0
-            ;;
-        minor)
-            ((minor++))
-            patch=0
-            ;;
-        patch)
-            ((patch++))
-            ;;
-        *)
-            echo "Error: $semverType is not a valid semver type" >&2
-            exit 1
-            ;;
+        major) ((major++)); minor=0; patch=0 ;;
+        minor) ((minor++)); patch=0 ;;
+        patch) ((patch++)) ;;
+        *) echo "Error: $semverType is not a valid semver type" >&2; exit 1 ;;
     esac
 
     version="v$major.$minor.$patch"
